// Precache metadata above is generated by build-chess-channel-pwas.py.
const ROOT = new URL('./', self.location.href);
const CACHE_NAME = PREFIX + RELEASE;
const CACHEABLE = new Set(ASSETS.map(path => new URL(path, ROOT).pathname));
CACHEABLE.add(ROOT.pathname);

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Install atomically: a failed asset fetch never activates the new worker.
    await cache.addAll(ASSETS.map(path => new Request(new URL(path, ROOT), { cache: 'reload' })));
    // Do not replace the active release while a game or study is open.
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'ACTIVATE_UPDATE') event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name !== CACHE_NAME && name.startsWith(PREFIX)) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  // CURRENT has a broad /chess/ scope. Never intercept LAB, PREVIOUS, archives,
  // APIs, tokens, or files outside the exact active-channel asset allowlist.
  if (url.origin !== ROOT.origin || !CACHEABLE.has(url.pathname)) return;
  const path = url.pathname === ROOT.pathname ? 'index.html' : url.pathname.slice(ROOT.pathname.length);
  const cacheKey = new URL(path, ROOT);
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Versioned asset queries resolve to the same installed release.
    return await cache.match(cacheKey) || fetch(request);
  })());
});
