import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {hash,validDate,authorForDate,localParts,validateRecord,validateCatalog,latestPage,monthlyPage,initialize,publish,loadRecords} from '../scripts/nara-daily.mjs';
function record(date='2026-10-05',published_at='2026-10-05T20:00:00Z'){const r={schema:'nara.daily.record.v1',id:'NARA-D-'+date,date,published_at,title:'Fixture only — not a real story',deck:'A local renderer test.',shape:'Test fixture',scenes:[{title:'A safe string',paragraphs:['<script>alert(1)</script>','A choice & its cost.']}],critic_line:'This is a test, not a peer review.'};r.content_sha256=hash(JSON.stringify({title:r.title,deck:r.deck,shape:r.shape,scenes:r.scenes}));return r}
function temp(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nara-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));initialize(root,'2026-10');return root}
test('dates reject invalid calendar days and traversal',()=>{for(const d of ['2026-02-30','2026-13-01','../2026-01-01','2026-1-01'])assert.equal(validDate(d),false);assert.equal(validDate('2028-02-29'),true)});
test('authors alternate across month and year boundaries',()=>{assert.equal(authorForDate('2026-10-05'),'CLAUDE');assert.equal(authorForDate('2026-10-06'),'GPT');assert.notEqual(authorForDate('2026-10-31'),authorForDate('2026-11-01'));assert.notEqual(authorForDate('2026-12-31'),authorForDate('2027-01-01'))});
test('22:00 stays local across autumn and spring DST',()=>{assert.equal(localParts('2026-10-24T20:00:00Z').hour,'22');assert.equal(localParts('2026-10-25T21:00:00Z').hour,'22');assert.equal(localParts('2027-03-27T21:00:00Z').hour,'22');assert.equal(localParts('2027-03-28T20:00:00Z').hour,'22')});
test('record and prose hash validate',()=>{assert.equal(validateRecord(record()).id,'NARA-D-2026-10-05');const r=record();r.scenes[0].paragraphs[0]='changed';assert.throws(()=>validateRecord(r),/hash mismatch/)});
test('private fields never enter public records',()=>{const r=record();r.drive_id='PRIVATE';assert.throws(()=>validateRecord(r),/unexpected\/private/)});
test('publication gate rejects missing peer closing line',()=>{const r=record();r.critic_line='';assert.throws(()=>validateRecord(r),/critic/)});
test('record rejects early local time and missing timezone',()=>{assert.throws(()=>validateRecord(record('2026-10-05','2026-10-05T19:59:00Z')),/before 22/);assert.throws(()=>validateRecord(record('2026-10-05','2026-10-05T22:00:00')),/timezone/)});
test('rendered peer text is inert and image-free',()=>{const r=record();const p=latestPage(r,'2026-10');assert.ok(p.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));assert.ok(!p.includes('<script>alert(1)'));assert.ok(!/<img\b|<iframe\b|<svg\b/i.test(p));assert.ok(p.includes(r.critic_line));assert.ok(p.includes('Nara-AI-2026-10.html#NARA-D-2026-10-05'))});
test('empty initialization does not invent a story',t=>{const root=temp(t);const {records,n}=loadRecords(root);assert.equal(records.length,0);assert.ok(fs.readFileSync(path.join(n,'Nara-AI-daily.html'),'utf8').includes('not published yet'));assert.throws(()=>initialize(root,'2026-99'),/invalid month/)});
test('publish is idempotent and conflicting replay fails',t=>{const root=temp(t);const r=record();assert.match(publish(root,r,new Date(r.published_at)),/LOCAL_CANDIDATE/);const state=fs.readFileSync(path.join(root,'public/Nara/daily/catalog.json'),'utf8');assert.equal(publish(root,r,new Date(r.published_at)),'ALREADY_PUBLISHED');assert.equal(fs.readFileSync(path.join(root,'public/Nara/daily/catalog.json'),'utf8'),state);const other=record();other.critic_line='changed';assert.throws(()=>publish(root,other,new Date(other.published_at)),/duplicate date/);assert.throws(()=>initialize(root,'2026-10'),/refuses/)});
test('old days and future timestamps cannot be published',t=>{const root=temp(t);assert.throws(()=>publish(root,record(),new Date('2026-10-05T19:59:00Z')),/future/);assert.throws(()=>publish(root,record(),new Date('2026-10-06T20:00:00Z')),/current local/)});
test('monthly HTML and latest have matching prose hash',t=>{const root=temp(t);publish(root,record(),new Date('2026-10-05T20:00:00Z'));const {n,records}=loadRecords(root);for(const f of ['Nara-AI-daily.html','Nara-AI-2026-10.html'])assert.ok(fs.readFileSync(path.join(n,f),'utf8').includes(records[0].content_sha256));assert.ok(monthlyPage('2026-10',records).includes('id="NARA-D-2026-10-05"'))});
test('catalog blocks duplicate dates and unsafe paths',()=>{const e={date:'2026-10-05',id:'NARA-D-2026-10-05',file:'daily/records/2026-10-05.json',title:'Test',record_sha256:'a'.repeat(64)};assert.throws(()=>validateCatalog({schema:'nara.daily.catalog.v1',records:[e,e]}),/duplicate/);assert.throws(()=>validateCatalog({schema:'nara.daily.catalog.v1',records:[{...e,file:'../secret'}]}),/unsafe/)});
test('byte corruption in stored records is rejected',t=>{const root=temp(t);publish(root,record(),new Date('2026-10-05T20:00:00Z'));fs.appendFileSync(path.join(root,'public/Nara/daily/records/2026-10-05.json'),' ');assert.throws(()=>loadRecords(root),/byte hash/)});
