import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {hash,validDate,authorForDate,localParts,validateRecord,validateCatalog,validateLog,latestPage,monthlyPage,logPage,initialize,publish,loadRecords} from '../scripts/nara-daily.mjs';

function record(date='2026-10-05',published_at='2026-10-05T20:00:00Z'){
  const r={schema:'nara.daily.record.v1',id:'NARA-D-'+date,date,published_at,title:'Fixture only — not a real story',deck:'A local renderer test.',shape:'Test fixture',scenes:[{title:'A safe string',paragraphs:['<script>alert(1)</script>','A choice & its cost.']}],critic_line:'This is a test, not a peer review.'};
  r.content_sha256=hash(JSON.stringify({title:r.title,deck:r.deck,shape:r.shape,scenes:r.scenes}));
  return r;
}
function logRecord(date='2026-10-05'){
  const candidates=Array.from({length:10},(_,i)=>({title:'Candidate '+(i+1),premise:'Distinct premise '+(i+1)+'.'}));
  return {schema:'nara.daily.log.v1',id:'NARA-D-'+date+'-LOG',date,story_id:'NARA-D-'+date,title:'Fixture only — not a real story',proposer:'GPT',selector:'CLAUDE',author:'GPT',critic:'CLAUDE',candidates,selection:{title:'Candidate 3',reason:'It creates the sharpest conflict.',risk:'Do not resolve it too easily.'},rounds:[{actor:'CLAUDE',stage:'STORY_SELECTION',summary:'Selected candidate 3 and named the central risk.'},{actor:'GPT',stage:'AUTHOR_DRAFT',summary:'Built a complete first draft.'},{actor:'CLAUDE',stage:'CRITIC_REVIEW',summary:'Pressed agency, third-party cost and the ending.'},{actor:'GPT',stage:'AUTHOR_REVISION',summary:'Reworked the middle and consequence.'},{actor:'GPT',stage:'AUTHOR_FINAL',summary:'Committed the final author pass.'},{actor:'CLAUDE',stage:'CRITIC_CLOSE',summary:'Closed the reviewed final with no hard blocker.'}],final_critic_line:'This is a test, not a peer review.'};
}
function temp(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nara-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));initialize(root,'2026-10');return root}

test('dates reject invalid calendar days and traversal',()=>{for(const d of ['2026-02-30','2026-13-01','../2026-01-01','2026-1-01'])assert.equal(validDate(d),false);assert.equal(validDate('2028-02-29'),true)});
test('authors alternate across month and year boundaries',()=>{assert.equal(authorForDate('2026-10-05'),'CLAUDE');assert.equal(authorForDate('2026-10-06'),'GPT');assert.notEqual(authorForDate('2026-10-31'),authorForDate('2026-11-01'));assert.notEqual(authorForDate('2026-12-31'),authorForDate('2027-01-01'))});
test('22:00 stays local across autumn and spring DST',()=>{assert.equal(localParts('2026-10-24T20:00:00Z').hour,'22');assert.equal(localParts('2026-10-25T21:00:00Z').hour,'22');assert.equal(localParts('2027-03-27T21:00:00Z').hour,'22');assert.equal(localParts('2027-03-28T20:00:00Z').hour,'22')});
test('record and prose hash validate',()=>{assert.equal(validateRecord(record()).id,'NARA-D-2026-10-05');const r=record();r.scenes[0].paragraphs[0]='changed';assert.throws(()=>validateRecord(r),/hash mismatch/)});
test('private fields never enter public story records',()=>{const r=record();r.drive_id='PRIVATE';assert.throws(()=>validateRecord(r),/unexpected\/private/)});
test('publication gate rejects missing peer closing line',()=>{const r=record();r.critic_line='';assert.throws(()=>validateRecord(r),/critic/)});
test('record rejects early local time and missing timezone',()=>{assert.throws(()=>validateRecord(record('2026-10-05','2026-10-05T19:59:00Z')),/before 22/);assert.throws(()=>validateRecord(record('2026-10-05','2026-10-05T22:00:00')),/timezone/)});
test('editorial log validates ten candidates and rejects private fields',()=>{assert.equal(validateLog(logRecord()).candidates.length,10);const short=logRecord();short.candidates.pop();assert.throws(()=>validateLog(short),/candidates/);const priv=logRecord();priv.task_id='PRIVATE';assert.throws(()=>validateLog(priv),/unexpected\/private/)});
test('log requires paired author and critic roles plus final close',()=>{const l=logRecord();l.selector='GPT';assert.throws(()=>validateLog(l),/pairing/);const missing=logRecord();missing.rounds=missing.rounds.filter(r=>r.stage!=='CRITIC_CLOSE');assert.throws(()=>validateLog(missing),/final\/close/)});
test('rendered peer text is inert and image-free',()=>{const r=record();const p=latestPage(r,'2026-10');assert.ok(p.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));assert.ok(!p.includes('<script>alert(1)'));assert.ok(!/<img\b|<iframe\b|<svg\b/i.test(p));assert.ok(p.includes(r.critic_line));assert.ok(p.includes('ILLUMINARA / DAILY'));assert.ok(p.includes('Nara-AI-log.html'))});
test('log page escapes summaries and exposes no operational fields',()=>{const l=logRecord();l.rounds[1].summary='<script>private()</script>';const p=logPage([l]);assert.ok(p.includes('&lt;script&gt;private()&lt;/script&gt;'));assert.ok(!p.includes('<script>private()'));assert.ok(!p.includes('drive_id'));assert.ok(p.includes('Illuminara Daily · Log'))});
test('empty initialization creates Daily, Archive and Log without inventing a story',t=>{const root=temp(t);const {records,n}=loadRecords(root);assert.equal(records.length,0);assert.ok(fs.readFileSync(path.join(n,'Nara-AI-daily.html'),'utf8').includes('not published yet'));assert.ok(fs.readFileSync(path.join(n,'Nara-AI-log.html'),'utf8').includes('not published yet'));assert.throws(()=>initialize(root,'2026-99'),/invalid month/)});
test('publish requires story and log to agree',t=>{const root=temp(t),r=record(),l=logRecord();l.title='Wrong';assert.throws(()=>publish(root,r,l,new Date(r.published_at)),/story\/log mismatch/);l.title=r.title;l.final_critic_line='Wrong';assert.throws(()=>publish(root,r,l,new Date(r.published_at)),/critic line mismatch/)});
test('publish writes seven outputs, is idempotent and conflicting replay fails',t=>{const root=temp(t),r=record(),l=logRecord();assert.match(publish(root,r,l,new Date(r.published_at)),/SEVEN_FILES/);const {n}=loadRecords(root);for(const f of ['daily/records/2026-10-05.json','daily/log/2026-10-05.json','daily/catalog.json','Nara-AI-daily.html','Nara-AI-2026-10.html','Nara-AI-archive.html','Nara-AI-log.html'])assert.ok(fs.existsSync(path.join(n,f)),f);const state=fs.readFileSync(path.join(n,'daily/catalog.json'),'utf8');assert.equal(publish(root,r,l,new Date(r.published_at)),'ALREADY_PUBLISHED');assert.equal(fs.readFileSync(path.join(n,'daily/catalog.json'),'utf8'),state);const other=logRecord();other.rounds[0].summary='changed';assert.throws(()=>publish(root,r,other,new Date(r.published_at)),/different log/)});
test('old days and future timestamps cannot be published',t=>{const root=temp(t),l=logRecord();assert.throws(()=>publish(root,record(),l,new Date('2026-10-05T19:59:00Z')),/future/);assert.throws(()=>publish(root,record(),l,new Date('2026-10-06T20:00:00Z')),/current local/)});
test('monthly, latest and log projections match the published story',t=>{const root=temp(t),r=record(),l=logRecord();publish(root,r,l,new Date(r.published_at));const {n,records}=loadRecords(root);for(const f of ['Nara-AI-daily.html','Nara-AI-2026-10.html'])assert.ok(fs.readFileSync(path.join(n,f),'utf8').includes(records[0].content_sha256));const lp=fs.readFileSync(path.join(n,'Nara-AI-log.html'),'utf8');assert.ok(lp.includes(l.selection.title));assert.ok(lp.includes('Read the published story'));assert.ok(monthlyPage('2026-10',records).includes('id="NARA-D-2026-10-05"'))});
test('catalog blocks duplicate dates, unsafe story paths and unsafe log paths',()=>{const e={date:'2026-10-05',id:'NARA-D-2026-10-05',file:'daily/records/2026-10-05.json',title:'Test',record_sha256:'a'.repeat(64),log_file:'daily/log/2026-10-05.json',log_sha256:'b'.repeat(64)};assert.throws(()=>validateCatalog({schema:'nara.daily.catalog.v1',records:[e,e]}),/duplicate/);assert.throws(()=>validateCatalog({schema:'nara.daily.catalog.v1',records:[{...e,file:'../secret'}]}),/unsafe record/);assert.throws(()=>validateCatalog({schema:'nara.daily.catalog.v1',records:[{...e,log_file:'../secret'}]}),/unsafe log/)});
test('byte corruption in stored story or log is rejected on replay',t=>{const root=temp(t),r=record(),l=logRecord();publish(root,r,l,new Date(r.published_at));const {n}=loadRecords(root);fs.appendFileSync(path.join(n,'daily/log/2026-10-05.json'),' ');assert.throws(()=>publish(root,r,l,new Date(r.published_at)),/different log/)});
