import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { webcrypto, createHash } from 'node:crypto';
import { JSDOM } from 'jsdom';
import { applyCommand, initialState } from '../functions/_wl/core.mjs';

const html=fs.readFileSync(new URL('../public/WL/BD/index.html',import.meta.url),'utf8');
const script=fs.readFileSync(new URL('../public/WL/BD/reader.js',import.meta.url),'utf8');
const encoder=new TextEncoder(),raw=webcrypto.getRandomValues(new Uint8Array(32)),at=new Date().toISOString();
const cryptoKey=await webcrypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']);
async function box(value,aad){const iv=webcrypto.getRandomValues(new Uint8Array(12));const cipher=Buffer.from(await webcrypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encoder.encode(aad)},cryptoKey,encoder.encode(JSON.stringify(value))));return {format:'WL-ENC-2',iv:Buffer.from(iv).toString('base64'),cipher:cipher.toString('base64'),sha256:createHash('sha256').update(cipher).digest('hex')}}
const fixtureVault={format:'WL-VAULT-2',vault_id:'synthetic-vault',control:await box({ok:true},'WL:control:synthetic-vault')};
const fixtureSummary=await box({schema:'wl.bd.summary.v1',generated_at_utc:at,frontiers:{email:{logical_messages:4,A_turn:2,B_turn:2},rhp:{events:1,event_id:'e000001'}},email:{title:'Synthetic email only',overview:'<img src=x onerror=alert(1)>',sections:[{heading:'Synthetic section',text:'private fixture sentence'}],assessment:'fixture assessment'},rhp:{title:'Synthetic Legacy only',overview:'fixture overview',sections:[],assessment:'fixture assessment'}},'WL:BD:summary:v1');
const fixtureState=await box({schema:'wl.state.v2',run_id:'WL-RHP11-20260912',revision:2,updated_at:at,entries:[{seq:1,event_id:'e000001',path:'data/entries/e000001.enc.json'},{seq:2,event_id:'e000002',path:'data/entries/e000002.enc.json'}]},'WL:state:synthetic-vault');
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,label){for(let i=0;i<150;i++){if(check())return;await pause(10)}throw Error('Timed out: '+label)}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}}
function setup(){
 const dom=new JSDOM(html,{url:'https://fixture.invalid/WL/BD/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.AbortController=AbortController;w.structuredClone=structuredClone;
 let holdDecrypt=null;Object.defineProperty(w.crypto,'subtle',{value:{importKey:(...a)=>webcrypto.subtle.importKey(...a),digest:(...a)=>webcrypto.subtle.digest(...a),deriveKey:(...a)=>webcrypto.subtle.deriveKey(...a),decrypt:async(...a)=>{if(holdDecrypt){const d=holdDecrypt;holdDecrypt=null;d.started.resolve();await d.release.promise}return webcrypto.subtle.decrypt(...a)}}});
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.sessionStorage.setItem('wl-v2-session',JSON.stringify({vault:'synthetic-vault',key:Buffer.from(raw).toString('base64')}));
 let state=initialState(),failAfterAccept=false,holdManaged=null;const requests=[],posts=[];
 function runs(){return [...Object.values(state.runs).map(r=>({...r,allowed_actions:r.status==='DRAFT'?['START','STOP','SOFT_DELETE']:r.status==='DELETED'?['RESTORE_FROM_ARCHIVE']:['STOP','PROLONG','PROLONG_AND_RESUME','SOFT_DELETE']})),{run_id:'synthetic-existing',run_kind:'LEGACY_WL',title:'<script>private synthetic title</script>',status:'BLOCKED',revision:0,control_epoch:0,original_worker_status:'OUTSIDE_MANAGED_CONTROL',projection_only:true,allowed_actions:[],counters:{accepted_turns:null},block_reason:'WORKER_BINDING_REQUIRED'}]}
 function managed(){return {ok:true,server_time:new Date().toISOString(),revision:state.revision,runs:runs(),capabilities:{create_new_wl:true,create_email_dialogue:true,email_recipients:[{id:'bd-owned-gmail-bdsim',label:'BD Gmail fixture'},{id:'bd-owned-outlook-llm',label:'BD Outlook fixture'}],new_run_note:'Durable drafts only; no activated worker.'},health:{last_control_observation_at:at},memory:{history_sync:'NOT_ACTIVATED'}}}
 w.fetch=async(url,opt={})=>{
  requests.push({url:String(url),method:opt.method||'GET',headers:opt.headers});
  if(String(url)==='/WL/vault.json')return response(fixtureVault);
  if(String(url)==='/WL/BD/summary.enc.json')return response(fixtureSummary);
  if(String(url)==='/WL/state.enc.json')return response(fixtureState);
  const parsed=new URL(url,w.location.href);if(parsed.pathname!=='/api/wl/managed')return response({ok:false,error:'NOT_FOUND'},404);
  if(opt.headers?.['x-wl-password']!=='synthetic-only-password')return response({ok:false,error:'UNAUTHORIZED'},401);
  if(opt.method==='POST'){
   const command=JSON.parse(opt.body);posts.push(command);const normalized={...command,control_epoch:command.expected_control_epoch};delete normalized.expected_control_epoch;
   try{const changed=applyCommand(state,normalized,{actor:{id:'BD',authenticated:true,role:'owner',auth_ref:'TEST_ONLY'},now:new Date().toISOString(),capabilities:{approved_recipient_ids:['bd-owned-gmail-bdsim','bd-owned-outlook-llm']}});state=changed.state;if(failAfterAccept){failAfterAccept=false;throw new TypeError('Synthetic transport disconnect')}return response({ok:true,receipt:changed.result})}
   catch(e){if(e instanceof TypeError)throw e;return response({ok:false,error:e.code||e.message},e.status||409)}
  }
  if(parsed.searchParams.has('command_id')){const receipt=state.commands[parsed.searchParams.get('command_id')];return receipt?response({ok:true,receipt}):response({ok:false,error:'COMMAND_NOT_FOUND'},404)}
  if(holdManaged){const d=holdManaged;holdManaged=null;d.started.resolve();await d.release.promise}
  return response(managed());
 };
 w.eval(script);const $=id=>w.document.getElementById(id);
 const submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 async function ready(){await until(()=>!$('app').hidden&&$('emailTitle').textContent==='Synthetic email only','read-only unlock')}
 async function authorize(){await ready();$('control-pw').value='synthetic-only-password';submit('control-login');await until(()=>!$('create-mission').disabled,'control authorization')}
 function fillMission(){ $('create-mission').click();$('create-title').value='Synthetic durable Mission';$('create-intent').value='Synthetic private research intent';$('target-artifact').value='Synthetic report';$('success-test').value='Synthetic receipt check';$('source-scope').value='Synthetic explicitly scoped source';$('source-requirements').value='Synthetic requirement'; }
 return {dom,w,$,submit,ready,authorize,fillMission,requests,posts,getState:()=>state,failNext:()=>{failAfterAccept=true},holdNextManaged:()=>{holdManaged={started:deferred(),release:deferred()};return holdManaged},holdNextDecrypt:()=>{holdDecrypt={started:deferred(),release:deferred()};return holdDecrypt}};
}

test('read-only key never grants controls; current encrypted state marks summary stale; XSS stays text',async()=>{const x=setup();try{await x.ready();await until(()=>x.$('summary-freshness').textContent.includes('e000002'),'state index comparison');assert.equal(x.$('control-login').hidden,false);assert.equal(x.$('create-mission').disabled,true);assert.equal(x.requests.some(r=>r.url==='/api/wl/managed'),false);assert.equal(x.$('emailOverview').textContent,'<img src=x onerror=alert(1)>');assert.equal(x.$('emailOverview').querySelector('img'),null);assert.match(x.$('summary-freshness').textContent,/ZASTARELO/);await x.authorize();assert.equal(x.$('control-pw').value,'');assert.match(x.$('run-list').textContent,/OUTSIDE_MANAGED_CONTROL/);assert.equal(x.$('run-list').querySelector('script'),null);assert.equal([...Array(x.w.sessionStorage.length).keys()].map(i=>x.w.sessionStorage.getItem(x.w.sessionStorage.key(i))).join('').includes('synthetic-only-password'),false);x.$('language').click();assert.match(x.$('run-list').textContent,/OUTSIDE_MANAGED_CONTROL/);assert.equal(x.w.document.documentElement.lang,'en')}finally{x.dom.window.close()}});

test('Mission creation and explicit Start use real core contract and CAS revisions',async()=>{const x=setup();try{await x.authorize();x.fillMission();x.submit('create-form');await until(()=>x.posts.length===1&&!x.$('create-dialog').open,'durable create');const c=x.posts[0];assert.equal(c.action,'CREATE');assert.equal(c.expected_revision,0);assert.equal(c.parameters.mission.cost_policy,'NO_PAID');assert.deepEqual(c.parameters.mission.allowed_effect_scope,['RESEARCH']);assert.deepEqual(c.parameters.mission.source_scope,['Synthetic explicitly scoped source']);assert.equal(c.parameters.duration_hours,168);assert.equal(x.getState().runs[c.run_id].status,'DRAFT');assert.equal(x.getState().runs[c.run_id].expires_at,null);await until(()=>[...x.$('run-list').querySelectorAll('button')].some(b=>b.textContent==='Start'),'start control');[...x.$('run-list').querySelectorAll('button')].find(b=>b.textContent==='Start').click();x.submit('action-form');await until(()=>x.posts.length===2&&!x.$('action-dialog').open,'start receipt');assert.equal(x.posts[1].action,'START');assert.equal(x.posts[1].expected_revision,1);assert.equal(x.posts[1].expected_control_epoch,1);assert.equal(x.getState().runs[c.run_id].status,'BLOCKED');assert.equal(x.getState().runs[c.run_id].block_reason,'WORKER_NOT_BOUND')}finally{x.dom.window.close()}});

test('uncertain accepted CREATE resolves original receipt without a second POST',async()=>{const x=setup();try{await x.authorize();x.fillMission();x.failNext();x.submit('create-form');await until(()=>!x.$('retry-panel').hidden,'retry shown');assert.equal(x.posts.length,1);const sent=x.posts[0];const durable=JSON.parse(x.w.sessionStorage.getItem('wl-bd-draft-ids-v1:NEW_WL'));assert.equal(durable.command_id,sent.command_id);assert.equal(Object.values(durable).includes('Synthetic private research intent'),false);x.$('retry-command').click();await until(()=>!x.$('create-dialog').open,'reconciled');assert.equal(x.posts.length,1);assert.ok(x.requests.some(r=>r.url.includes('?command_id='+sent.command_id)));assert.equal(Object.keys(x.getState().runs).length,1);assert.equal(x.w.sessionStorage.getItem('wl-bd-draft-ids-v1:NEW_WL'),null)}finally{x.dom.window.close()}});

test('email creation sends only explicit allowlist IDs and no arbitrary addresses',async()=>{const x=setup();try{await x.authorize();x.$('create-email').click();x.$('create-title').value='Synthetic email';x.$('create-intent').value='Synthetic seed';for(const o of x.$('email-recipients').options)o.selected=true;x.submit('create-form');await until(()=>x.posts.length===1&&!x.$('create-dialog').open,'email create');assert.deepEqual(x.posts[0].parameters.recipients,['bd-owned-gmail-bdsim','bd-owned-outlook-llm']);assert.equal(x.posts[0].parameters.run_kind,'EMAIL_DIALOGUE');assert.equal(x.posts[0].parameters.mission,undefined);assert.equal(x.getState().runs[x.posts[0].run_id].status,'DRAFT')}finally{x.dom.window.close()}});

test('lock clears decrypted DOM, form data, session key and delayed managed response cannot repopulate',async()=>{const x=setup();try{await x.authorize();x.fillMission();const d=x.holdNextManaged();x.$('refresh').click();await d.started.promise;x.$('lock').click();d.release.resolve();await pause(60);assert.equal(x.$('app').hidden,true);assert.equal(x.$('gate').hidden,false);assert.equal(x.$('run-list').textContent,'');assert.equal(x.$('emailOverview').textContent,'');assert.equal(x.$('create-intent').value,'');assert.equal(x.$('control-pw').value,'');assert.equal(x.w.sessionStorage.getItem('wl-v2-session'),null);assert.equal(x.$('create-dialog').open,false);assert.equal(x.$('run-list').querySelectorAll('*').length,0);assert.equal(x.w.document.body.textContent.includes('Synthetic email only'),false)}finally{x.dom.window.close()}});

test('lock during pending decrypt prevents private summary from returning',async()=>{const x=setup();try{await x.authorize();const d=x.holdNextDecrypt();x.$('refresh').click();await d.started.promise;x.$('lock').click();d.release.resolve();await pause(60);assert.equal(x.$('emailTitle').textContent,'');assert.equal(x.$('rhpTitle').textContent,'');assert.equal(x.$('app').hidden,true);assert.equal(x.w.document.body.textContent.includes('private fixture sentence'),false)}finally{x.dom.window.close()}});

test('tab keyboard selection and font bounds are operable without pointer input',async()=>{const x=setup();try{await x.authorize();x.$('tab-ALL').dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(x.$('tab-NEW_WL').getAttribute('aria-selected'),'true');assert.equal(x.w.document.activeElement.id,'tab-NEW_WL');for(let i=0;i<30;i++)x.$('plus').click();assert.equal(x.$('reset').textContent,'200%');x.$('theme').click();assert.equal(x.w.document.documentElement.dataset.theme,'light');x.$('reset').click();assert.equal(x.$('reset').textContent,'100%')}finally{x.dom.window.close()}});

test('prolong uses explicit duration, soft delete needs confirmation and restore leaves run stopped',async()=>{const x=setup();try{await x.authorize();x.fillMission();x.submit('create-form');await until(()=>x.posts.length===1&&!x.$('create-dialog').open,'create');const id=x.posts[0].run_id;const clickAction=label=>{const button=[...x.$('run-list').querySelectorAll('button')].find(b=>b.textContent===label);assert.ok(button,'action '+label);button.click()};clickAction('Start');x.submit('action-form');await until(()=>x.posts.length===2&&!x.$('action-dialog').open,'start');const end=x.getState().runs[id].expires_at;clickAction('Podaljšaj');x.$('prolong-days').value='1';x.submit('action-form');await until(()=>x.posts.length===3&&!x.$('action-dialog').open,'prolong');assert.equal(x.posts[2].parameters.duration_hours,24);assert.equal(Date.parse(x.getState().runs[id].expires_at)-Date.parse(end),24*3600000);assert.equal(x.getState().runs[id].status,'BLOCKED');clickAction('Izbriši / arhiviraj');assert.equal(x.posts.length,3);assert.match(x.$('action-description').textContent,/dokazi ostanejo/);x.submit('action-form');await until(()=>x.posts.length===4&&!x.$('action-dialog').open,'soft delete');assert.equal(x.getState().runs[id].status,'DELETED');x.$('tab-ARCHIVE').click();clickAction('Obnovi iz arhiva');x.submit('action-form');await until(()=>x.posts.length===5&&!x.$('action-dialog').open,'restore');assert.equal(x.getState().runs[id].status,'STOPPED');assert.equal(x.getState().runs[id].deleted_at,null)}finally{x.dom.window.close()}});
