"""Rebuild the nine supplied National TSPs as explicitly georeferenced Maps data.

Usage: python scripts/build-trip-tsp.py
The original EUC_2D objective is deliberately NOT reproduced by the Maps adapter.
"""
from pathlib import Path
from decimal import Decimal
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1] / "public/Trip/new"
# Raw country files store absolute decimal degrees multiplied by 1000.
# Restore the known hemisphere per dataset; this is not a generic EUC_2D converter.
DATASETS = [
    ("wi29", "Western Sahara", "Zahodna Sahara", 29, 1, -1),
    ("dj38", "Djibouti", "Džibuti", 38, 1, 1),
    ("qa194", "Qatar", "Katar", 194, 1, 1),
    ("uy734", "Uruguay", "Urugvaj", 734, -1, -1),
    ("zi929", "Zimbabwe", "Zimbabve", 929, -1, 1),
    ("lu980", "Luxembourg", "Luksemburg", 980, 1, 1),
    ("rw1621", "Rwanda", "Ruanda", 1621, -1, 1),
    ("mu1979", "Oman", "Oman", 1979, 1, 1),
    ("nu3496", "Nicaragua", "Nikaragva", 3496, 1, -1),
]
catalog = []
for code, name, sl, count, lat_sign, lon_sign in DATASETS:
    raw = (ROOT / "tsp" / (code + ".tsp")).read_bytes()
    text = raw.decode("utf-8")
    assert re.search(r"EDGE_WEIGHT_TYPE\s*:\s*EUC_2D", text), code
    assert int(re.search(r"DIMENSION\s*:\s*(\d+)", text)[1]) == count, code
    points = []
    for row in text.split("NODE_COORD_SECTION", 1)[1].splitlines():
        row = row.strip()
        if not row or row == "EOF":
            continue
        node, x, y = row.split()
        x, y = Decimal(x), Decimal(y)
        assert x >= 0 and y >= 0, code
        lat, lon = float(x * lat_sign / 1000), float(y * lon_sign / 1000)
        assert -90 <= lat <= 90 and -180 <= lon <= 180, code
        points.append([int(node), lat, lon])
    assert len(points) == count and len({p[0] for p in points}) == count, code
    entry = dict(id=code, name=name, sl=sl, count=count,
                 distinctCoordinates=len({tuple(p[1:]) for p in points}),
                 originalMetric="EUC_2D", mapsMetric="great-circle-km",
                 scale=0.001, latitudeSign=lat_sign, longitudeSign=lon_sign,
                 originalSha256=hashlib.sha256(raw).hexdigest())
    catalog.append(entry)
    (ROOT / "tsp" / (code + ".json")).write_text(
        json.dumps(dict(id=code, points=points), separators=(",", ":")) + "\n")
(ROOT / "tsp-catalog.js").write_text(
    "/* Generated by scripts/build-trip-tsp.py; original node IDs and duplicate coordinates are retained. */\n"
    + "window.TRIP_TSP_CATALOG = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n")
print(f"Built {len(catalog)} datasets, {sum(e['count'] for e in catalog):,} nodes.")
