/** Nara Daily R1. Offline deterministic renderer; no network, email, AI or Git writes.
 * CLI: node scripts/nara-daily.mjs init <repoRoot> <YYYY-MM>
 *      node scripts/nara-daily.mjs publish <repoRoot> <verified-public-record.json>
 *      node scripts/nara-daily.mjs check <repoRoot>
 * Peer authenticity and editorial review MUST be verified by the publishing worker.
 */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
export const VERSION='nara-daily-r1';
export const BASE='https://bd-chess.github.io/bd-chessdb/Nara/';
export const hash=s=>crypto.createHash('sha256').update(s,'utf8').digest('hex');
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assert=(x,m)=>{if(!x)throw Error(m)};
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s}
export function authorForDate(s){assert(validDate(s),'invalid story date');const days=(Date.parse(s+'T00:00:00Z')-Date.parse('2026-10-05T00:00:00Z'))/86400000;return days%2===0?'CLAUDE':'GPT'}
export function localParts(s){const d=new Date(s);assert(Number.isFinite(d.getTime()),'invalid publication time');return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Ljubljana',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
const text=(s,n)=>typeof s==='string'&&s.trim().length>0&&s.length<=n;
export function validateRecord(r){assert(r&&r.schema==='nara.daily.record.v1','record schema');const keys=['schema','id','date','published_at','title','deck','shape','scenes','critic_line','content_sha256'];assert(Object.keys(r).every(k=>keys.includes(k)),'unexpected/private record field');assert(validDate(r.date),'invalid date');assert(r.id==='NARA-D-'+r.date,'id/date mismatch');assert(text(r.published_at,40)&&/(Z|[+-]\d\d:\d\d)$/.test(r.published_at),'timezone required');const t=localParts(r.published_at);assert(`${t.year}-${t.month}-${t.day}`===r.date&&Number(t.hour)>=22,'publication before 22:00 or wrong local date');assert(text(r.title,180)&&text(r.deck,500)&&text(r.shape,600),'title/deck/shape');assert(text(r.critic_line,700),'missing critic closing line');assert(Array.isArray(r.scenes)&&r.scenes.length>=1&&r.scenes.length<=12,'scene count');for(const s of r.scenes){assert(Object.keys(s).every(k=>['title','paragraphs'].includes(k)),'unexpected scene field');assert(text(s.title,180)&&Array.isArray(s.paragraphs)&&s.paragraphs.length>0,'scene structure');assert(s.paragraphs.every(p=>text(p,10000)),'paragraph structure')}const body=JSON.stringify({title:r.title,deck:r.deck,shape:r.shape,scenes:r.scenes});assert(r.content_sha256===hash(body),'story content hash mismatch');assert(JSON.stringify(r).length<=100000,'record too large');return r}
export function validateCatalog(c){assert(c?.schema==='nara.daily.catalog.v1'&&Array.isArray(c.records),'catalog schema');const seen=new Set();for(const e of c.records){assert(validDate(e.date)&&e.id==='NARA-D-'+e.date,'catalog identity');assert(!seen.has(e.date),'duplicate publication date');seen.add(e.date);assert(e.file===`daily/records/${e.date}.json`,'unsafe record path');assert(text(e.title,180)&&/^[a-f0-9]{64}$/.test(e.record_sha256),'catalog metadata')}return c}
const footer=`<footer class="footer wrap"><p>Illuminara fiction from the GPT × Claude creative line. Original Nara / Illuminara world: Bojan Dobrečevič.</p><p>Daily publication is not canon approval. BD and the editorial partner select stories for separate illustrated editions. No connection to grounded Nara is implied.</p><p><a href="index.html">Main Nara collection</a> · <a href="Nara-AI-daily.html">Latest story</a> · <a href="Nara-AI-archive.html">All months</a></p></footer>`;
const tools=`<div class="tools" role="group" aria-label="Reading controls"><button type="button" data-scale="-0.1" aria-label="Smaller story text">A−</button><output data-scale-label aria-live="polite">100%</output><button type="button" data-scale="0.1" aria-label="Larger story text">A+</button><button type="button" data-scale="reset" aria-label="Reset story text size">Reset</button><button type="button" data-theme-toggle>Day mode</button></div>`;
function shell(title,file,body,active='daily'){return `<!doctype html>\n<html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark light"><meta name="theme-color" content="#080d15"><title>${esc(title)} — Nara Daily</title><meta name="description" content="Text-only Illuminara stories from GPT and Claude. Scheduled nightly at 22:00 Europe/Ljubljana; separate from the curated illustrated canon."><link rel="canonical" href="${BASE+file}"><link rel="stylesheet" href="assets/css/nara-daily.css"><script defer src="assets/js/nara-daily-reader.js"></script><!-- ${VERSION}; generated, text-only --></head><body><a class="skip" href="#main">Skip to story</a><header class="bar"><div class="bar-inner"><a class="brand" href="index.html">NARA / DAILY</a><nav class="nav" aria-label="Primary"><a href="index.html">Main collection</a><a href="illuminara.html">Illuminara</a><a href="Nara-AI-daily.html"${active==='daily'?' aria-current="page"':''}>Daily</a><a href="Nara-AI-archive.html"${active==='archive'?' aria-current="page"':''}>Archive</a></nav></div></header><main class="wrap" id="main" tabindex="-1">${body}</main>${footer}</body></html>\n`}
const prose=r=>`<article class="story" data-story-id="${r.id}" data-content-sha256="${r.content_sha256}" aria-label="Story">${r.scenes.map((s,i)=>`<section><h2>${String(i+1).padStart(2,'0')} · ${esc(s.title)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('\n')}</section>`).join('\n')}</article>`;
const notes=r=>`<aside class="notes" aria-label="Editorial notes"><details><summary>What the critic still says doesn't work</summary><div class="inside"><p>${esc(r.critic_line)}</p></div></details><details><summary>Tonight's shape</summary><div class="inside"><p>${esc(r.shape)}</p></div></details></aside>`;
export function latestPage(r,month){return shell(r?r.title:'A story at the edge of night','Nara-AI-daily.html',r?`<header class="masthead"><div class="eyebrow">Latest published story · experimental Illuminara fiction</div><h1>${esc(r.title)}</h1><p class="lede">${esc(r.deck)}</p><p class="meta"><time datetime="${esc(r.published_at)}">${r.date}</time> · Nightly release: 22:00 Europe/Ljubljana · Text only</p>${tools}</header>${prose(r)}${notes(r)}<nav class="end-nav" aria-label="Story archive"><a href="Nara-AI-${r.date.slice(0,7)}.html#${r.id}">Permanent archive link</a><a href="Nara-AI-archive.html">All stories</a></nav>`:`<header class="masthead"><div class="eyebrow">Text-only Illuminara fiction · 22:00 Europe/Ljubljana</div><h1>A story at the edge of night.</h1><p class="lede">One author. One critic. A new attempt at the impossible conversation.</p>${tools}</header><section class="notice"><h2>The first story is not published yet.</h2><p>This reading lane is ready for the first completed GPT ↔ Claude cycle. Stories are released at the nightly 22:00 slot, only after the author and critic have both contributed.</p><p>A draft or a missing peer review will never be presented as a finished collaboration. Once a story is published, it remains here, clearly dated, until the next complete edition.</p></section><nav class="end-nav"><a href="Nara-AI-${month}.html">This month's archive</a><a href="index.html">Read the illustrated collection</a></nav>`)}
export function monthlyPage(month,records){assert(/^\d{4}-(0[1-9]|1[0-2])$/.test(month),'invalid month');return shell(month+' archive',`Nara-AI-${month}.html`,`<header class="masthead"><div class="eyebrow">Nightly stories · preserved editions</div><h1>${month}</h1><p class="lede">Open a date to read its complete story. Daily originals remain here when a separate illustrated edition is selected.</p>${tools}</header>${records.length?records.map(r=>`<details class="archive-item" id="${r.id}"><summary><time datetime="${r.date}">${r.date}</time><strong>${esc(r.title)}</strong></summary><div class="inside"><p class="lede">${esc(r.deck)}</p><p class="meta">Published ${esc(r.published_at)} · <a href="#${r.id}">Permanent link</a></p>${prose(r)}${notes(r)}</div></details>`).join('\n'):'<section class="notice"><h2>No published stories yet.</h2><p>Only completed, actually published stories appear in this archive. There are no invented entries for missed days.</p></section>'}`,'archive')}
export function archivePage(entries,emptyMonth){const months=[...new Set(entries.map(e=>e.date.slice(0,7)).concat(emptyMonth?[emptyMonth]:[]))].sort().reverse();return shell('The nightly archive','Nara-AI-archive.html',`<header class="masthead"><div class="eyebrow">Illuminara · text-only experiments</div><h1>The nightly archive</h1><p class="lede">A shelf of complete stories. A place to return, not a feed to keep up with.</p></header><ul class="months">${months.map(m=>`<li><a href="Nara-AI-${m}.html"><strong>${m}</strong><br><span class="muted">${entries.filter(e=>e.date.startsWith(m)).length} published stories</span></a></li>`).join('')}</ul><section class="notice"><h2>Daily first. Illustrated by choice.</h2><p>These stories belong to the experimental Illuminara lane. BD and the editorial partner may choose a story for a separately approved illustrated edition. The Daily original is retained; nothing becomes canon automatically.</p></section>`,'archive')}
function write(p,s){fs.mkdirSync(path.dirname(p),{recursive:true});if(fs.existsSync(p)&&fs.readFileSync(p,'utf8')===s)return;const tmp=p+'.tmp';fs.writeFileSync(tmp,s);fs.renameSync(tmp,p)}
const stringify=x=>JSON.stringify(x,null,2)+'\n';
export function loadRecords(root){const n=path.join(root,'public/Nara');const c=validateCatalog(JSON.parse(fs.readFileSync(path.join(n,'daily/catalog.json'),'utf8')));return {n,c,records:c.records.map(e=>{const bytes=fs.readFileSync(path.join(n,e.file),'utf8');assert(hash(bytes)===e.record_sha256,'record byte hash mismatch');const r=validateRecord(JSON.parse(bytes));assert(r.id===e.id&&r.date===e.date&&r.title===e.title,'catalog record mismatch');return r}).sort((a,b)=>b.date.localeCompare(a.date))}}
export function initialize(root,month){assert(/^\d{4}-(0[1-9]|1[0-2])$/.test(month),'invalid month');const n=path.join(root,'public/Nara');const cp=path.join(n,'daily/catalog.json');if(!fs.existsSync(cp))write(cp,stringify({schema:'nara.daily.catalog.v1',records:[]}));const {c,records}=loadRecords(root);assert(records.length===0,'init refuses existing stories');write(path.join(n,'Nara-AI-daily.html'),latestPage(null,month));write(path.join(n,`Nara-AI-${month}.html`),monthlyPage(month,[]));write(path.join(n,'Nara-AI-archive.html'),archivePage(c.records,month));return 'INITIALIZED_EMPTY_NOT_STORY_PUBLISHED'}
export function publish(root,record,now=new Date()){const r=validateRecord(record);assert(new Date(r.published_at).getTime()<=now.getTime(),'future publication time');const p=localParts(now.toISOString());assert(`${p.year}-${p.month}-${p.day}`===r.date&&Number(p.hour)>=22,'not current local 22:00 release window');const {n,c,records}=loadRecords(root);const bytes=stringify(r);const existing=c.records.find(e=>e.date===r.date);if(existing){assert(existing.record_sha256===hash(bytes),'duplicate date with different contents');return 'ALREADY_PUBLISHED'}assert(!records.some(x=>x.date>r.date),'backfill prohibited');const file=`daily/records/${r.date}.json`;const fp=path.join(n,file);if(fs.existsSync(fp))assert(fs.readFileSync(fp,'utf8')===bytes,'orphan conflict');const next=[r,...records].sort((a,b)=>b.date.localeCompare(a.date));const entries=[...c.records,{id:r.id,date:r.date,title:r.title,file,record_sha256:hash(bytes)}].sort((a,b)=>b.date.localeCompare(a.date));const month=r.date.slice(0,7);const outputs={[file]:bytes,'Nara-AI-daily.html':latestPage(next[0],month),[`Nara-AI-${month}.html`]:monthlyPage(month,next.filter(x=>x.date.startsWith(month))),'Nara-AI-archive.html':archivePage(entries,month),'daily/catalog.json':stringify({schema:'nara.daily.catalog.v1',records:entries})};for(const [rel,data]of Object.entries(outputs))write(path.join(n,rel),data);return 'LOCAL_CANDIDATE_READY_COMMIT_ALL_FIVE_FILES_ATOMICALLY'}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const [cmd,root,arg]=process.argv.slice(2);assert(root,'repoRoot required');if(cmd==='init')console.log(initialize(root,arg));else if(cmd==='publish')console.log(publish(root,JSON.parse(fs.readFileSync(arg,'utf8'))));else if(cmd==='check'){const {records}=loadRecords(root);console.log(JSON.stringify({schema:'nara.daily.validation.v1',records:records.length,result:'STATIC_VALID',peer_authenticity:'NOT_CHECKED_BY_RENDERER'}))}else throw Error('use init, publish or check')}catch(e){console.error(e.message);process.exitCode=1}}
