/** Illuminara Daily R2. Offline deterministic renderer; no network, email, AI or Git writes.
 * CLI: node scripts/nara-daily.mjs init <repoRoot> <YYYY-MM>
 *      node scripts/nara-daily.mjs publish <repoRoot> <verified-public-record.json> <verified-public-log.json>
 *      node scripts/nara-daily.mjs check <repoRoot>
 * Peer authenticity and editorial review MUST be verified by the publishing worker.
 */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
export const VERSION='illuminara-daily-r12-final-only';
export const BASE='https://bd-chess.github.io/bd-chessdb/Nara/';
export const hash=s=>crypto.createHash('sha256').update(s,'utf8').digest('hex');
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assert=(x,m)=>{if(!x)throw Error(m)};
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s}
export function authorForDate(s){assert(validDate(s),'invalid story date');const days=(Date.parse(s+'T00:00:00Z')-Date.parse('2026-10-05T00:00:00Z'))/86400000;return days%2===0?'GPT':'CLAUDE'}
export function localParts(s){const d=new Date(s);assert(Number.isFinite(d.getTime()),'invalid publication time');return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Ljubljana',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
const text=(s,n)=>typeof s==='string'&&s.trim().length>0&&s.length<=n;
const validateRevision=(v,date)=>{
  const keys=['date','edition','original_url','original_log_url'];
  assert(v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&Object.keys(v).every(k=>keys.includes(k)),'revision fields');
  assert(validDate(v.date)&&v.date>=date&&/^R[1-9][0-9]*$/.test(v.edition),'revision identity');
  assert(v.original_url===`Nara-AI-${date}-original.html`&&v.original_log_url===`Nara-AI-${date}-original-log.html`,'unsafe original edition path');
};
const validateLiteraryScore=x=>{assert(x&&typeof x==='object'&&!Array.isArray(x),'literary score');const keys=['combined','display','method','blind','weights','shared_strengths','shared_reservations'];assert(Object.keys(x).every(k=>keys.includes(k)),'unexpected literary score field');assert(typeof x.combined==='number'&&x.combined>=0&&x.combined<=100,'combined score range');assert(Number.isInteger(x.display)&&x.display>=0&&x.display<=100,'display score range');assert(x.display===Math.floor(x.combined+0.5),'display rounding');assert(x.blind===true,'score must be blind');assert(x.weights&&x.weights.gpt===0.5&&x.weights.claude===0.5,'score weights');assert(text(x.method,240),'score method');for(const k of ['shared_strengths','shared_reservations'])assert(Array.isArray(x[k])&&x[k].length>=1&&x[k].length<=6&&x[k].every(v=>text(v,600)),'score summary')};
const validateEvaluation=x=>{assert(x&&typeof x==='object'&&!Array.isArray(x),'evaluation');const keys=['blind','method','gpt','claude','weights','combined','display','note'];assert(Object.keys(x).every(k=>keys.includes(k)),'unexpected evaluation field');assert(x.blind===true&&x.method==='equal_weight_mean','evaluation method');for(const k of ['gpt','claude']){const v=x[k];assert(v&&Number.isInteger(v.score)&&v.score>=0&&v.score<=100&&text(v.rubric,180),'evaluation component')}assert(x.weights?.gpt===0.5&&x.weights?.claude===0.5,'evaluation weights');const mean=(x.gpt.score+x.claude.score)/2;assert(x.combined===mean,'evaluation mean');assert(x.display===Math.floor(mean+0.5),'evaluation display');assert(text(x.note,500),'evaluation note')};
const validateTranslationSl=(tr,r)=>{assert(tr&&typeof tr==='object'&&!Array.isArray(tr),'translation_sl');const keys=['title','deck','shape','scenes','critic_line','content_sha256'];assert(Object.keys(tr).every(k=>keys.includes(k))&&Object.keys(tr).length===keys.length,'translation_sl fields');assert(text(tr.title,180)&&text(tr.deck,700)&&text(tr.shape,900)&&text(tr.critic_line,900),'translation_sl text');assert(Array.isArray(tr.scenes)&&tr.scenes.length===r.scenes.length,'translation_sl scene count');for(let i=0;i<tr.scenes.length;i++){const a=tr.scenes[i],b=r.scenes[i];assert(a&&Object.keys(a).every(k=>['title','paragraphs'].includes(k)),'translation_sl scene field');assert(text(a.title,220)&&Array.isArray(a.paragraphs)&&a.paragraphs.length===b.paragraphs.length,'translation_sl scene structure');assert(a.paragraphs.every(p=>text(p,12000)),'translation_sl paragraph')}const body=JSON.stringify({title:tr.title,deck:tr.deck,shape:tr.shape,scenes:tr.scenes});assert(tr.content_sha256===hash(body),'translation_sl content hash mismatch')};
export function validateRecord(r){assert(r&&r.schema==='nara.daily.record.v1','record schema');const keys=['schema','id','date','published_at','title','deck','shape','scenes','critic_line','content_sha256','literary_score','translation_sl','revision'];assert(Object.keys(r).every(k=>keys.includes(k)),'unexpected/private record field');assert(validDate(r.date),'invalid date');assert(r.id==='NARA-D-'+r.date,'id/date mismatch');assert(text(r.published_at,40)&&/(Z|[+-]\d\d:\d\d)$/.test(r.published_at),'timezone required');const t=localParts(r.published_at);assert(`${t.year}-${t.month}-${t.day}`===r.date,'publication timestamp on wrong local date');assert(text(r.title,180)&&text(r.deck,500)&&text(r.shape,600),'title/deck/shape');assert(text(r.critic_line,700),'missing critic closing line');if(r.revision!==undefined)validateRevision(r.revision,r.date);if(r.literary_score!==undefined)validateLiteraryScore(r.literary_score);if(r.translation_sl!==undefined)validateTranslationSl(r.translation_sl,r);assert(Array.isArray(r.scenes)&&r.scenes.length>=1&&r.scenes.length<=12,'scene count');for(const s of r.scenes){assert(Object.keys(s).every(k=>['title','paragraphs'].includes(k)),'unexpected scene field');assert(text(s.title,180)&&Array.isArray(s.paragraphs)&&s.paragraphs.length>0,'scene structure');assert(s.paragraphs.every(p=>text(p,10000)),'paragraph structure')}const body=JSON.stringify({title:r.title,deck:r.deck,shape:r.shape,scenes:r.scenes});assert(r.content_sha256===hash(body),'story content hash mismatch');assert(JSON.stringify(r).length<=100000,'record too large');return r}
export function validateCatalog(c){assert(c?.schema==='nara.daily.catalog.v1'&&Array.isArray(c.records),'catalog schema');const seen=new Set();for(const e of c.records){assert(validDate(e.date)&&e.id==='NARA-D-'+e.date,'catalog identity');assert(!seen.has(e.date),'duplicate publication date');seen.add(e.date);assert(e.file===`daily/records/${e.date}.json`,'unsafe record path');assert(text(e.title,180)&&/^[a-f0-9]{64}$/.test(e.record_sha256),'catalog metadata');if(e.revision!==undefined)validateRevision(e.revision,e.date);if(e.log_file!==undefined||e.log_sha256!==undefined){assert(e.log_file===`daily/log/${e.date}.json`,'unsafe log path');assert(/^[a-f0-9]{64}$/.test(e.log_sha256),'log metadata')}}return c}
export function validateLog(l){assert(l&&l.schema==='nara.daily.log.v1','log schema');const keys=['schema','id','date','story_id','title','proposer','selector','author','critic','candidates','selection','rounds','final_critic_line','evaluation','revision'];assert(Object.keys(l).every(k=>keys.includes(k)),'unexpected/private log field');assert(validDate(l.date),'invalid log date');assert(l.id==='NARA-D-'+l.date+'-LOG'&&l.story_id==='NARA-D-'+l.date,'log identity');for(const k of ['proposer','selector','author','critic'])assert(['GPT','CLAUDE'].includes(l[k]),'log role');assert(l.proposer===l.author&&l.selector===l.critic&&l.author!==l.critic,'log role pairing');assert(text(l.title,180),'log title');assert(Array.isArray(l.candidates)&&l.candidates.length===10,'log candidates');for(const c of l.candidates){assert(c&&Object.keys(c).every(k=>['title','premise'].includes(k)),'candidate field');assert(text(c.title,180)&&text(c.premise,1200),'candidate text')}assert(l.selection&&Object.keys(l.selection).every(k=>['title','reason','risk'].includes(k)),'selection field');assert(text(l.selection.title,180)&&text(l.selection.reason,1200)&&text(l.selection.risk,1200),'selection text');assert(l.candidates.some(c=>c.title===l.selection.title),'selected candidate missing');assert(Array.isArray(l.rounds)&&l.rounds.length>=3&&l.rounds.length<=40,'log rounds');const stages=new Set(['STORY_SELECTION','AUTHOR_DRAFT','CRITIC_REVIEW','AUTHOR_REVISION','AUTHOR_FINAL','CRITIC_CLOSE']);for(const r of l.rounds){assert(r&&Object.keys(r).every(k=>['actor','stage','summary'].includes(k)),'round field');assert(['GPT','CLAUDE'].includes(r.actor)&&stages.has(r.stage)&&text(r.summary,1800),'round content')}assert(l.rounds.some(r=>r.stage==='AUTHOR_FINAL')&&l.rounds.some(r=>r.stage==='CRITIC_CLOSE'),'log missing final/close');assert(text(l.final_critic_line,700),'log critic line');if(l.revision!==undefined)validateRevision(l.revision,l.date);if(l.evaluation!==undefined)validateEvaluation(l.evaluation);assert(JSON.stringify(l).length<=80000,'log too large');return l}
// Translations are separate editions; the published English record stays immutable.
export function validateTranslation(t,r){
  assert(t?.schema==='nara.daily.translation.v1'&&t.language==='sl','translation schema/language');
  assert(t.story_id===r.id&&t.date===r.date,'translation identity');
  assert(t.source_content_sha256===r.content_sha256,'translation source mismatch');
  for(const k of ['title','deck','shape','critic_line'])assert(text(t[k],10000),'translation '+k);
  assert(Array.isArray(t.scenes)&&t.scenes.length===r.scenes.length,'translation scene count');
  t.scenes.forEach((s,i)=>{
    assert(text(s.title,180)&&Array.isArray(s.paragraphs)&&s.paragraphs.length===r.scenes[i].paragraphs.length,'translation paragraph count');
    assert(s.paragraphs.every(p=>text(p,10000)),'translation paragraph');
  });
  const body=JSON.stringify({title:t.title,deck:t.deck,shape:t.shape,scenes:t.scenes});
  assert(t.content_sha256===hash(body),'translation content hash mismatch');
  assert(text(t.translated_by,80),'translation attribution');
  if(t.literary_score){
    assert(r.literary_score&&text(t.literary_score.method,500),'translation score method');
    for(const k of ['shared_strengths','shared_reservations'])assert(Array.isArray(t.literary_score[k])&&t.literary_score[k].length===r.literary_score[k].length&&t.literary_score[k].every(v=>text(v,1000)),'translation score summary');
  }
  return t;
}
export function loadTranslations(root,records){
  const translations={};
  for(const r of records){
    const p=path.join(root,'public/Nara/daily/translations/sl',r.date+'.json');
    if(fs.existsSync(p))translations[r.id]=validateTranslation(JSON.parse(fs.readFileSync(p,'utf8')),r);
  }
  return translations;
}
const bi=(en,sl)=>'<span data-language-content="en" lang="en">'+esc(en)+'</span><span data-language-content="sl" lang="sl" hidden>'+esc(sl)+'</span>';
const aria=(en,sl)=>' aria-label="'+esc(en)+'" data-aria-en="'+esc(en)+'" data-aria-sl="'+esc(sl)+'"';
function footer(localized){
  const b=localized?bi:(en)=>esc(en);
  return '<footer class="footer wrap"><p>'+b('Illuminara fiction from the GPT × Claude creative line. Original Nara / Illuminara world: Bojan Dobrečevič.','Illuminarine zgodbe iz ustvarjalnega sodelovanja GPT × Claude. Izvirni svet Nara / Illuminara: Bojan Dobrečevič.')+'</p><p>'+b('Daily publication is not canon approval. BD and the editorial partner select stories for separate illustrated editions. No connection to grounded Nara is implied.','Dnevna objava ne pomeni potrditve za kanon. BD in uredniški partner izbirata zgodbe za ločene ilustrirane izdaje. Povezava s prizemljeno Naro ni nakazana.')+'</p><p><a href="index.html">'+b('Main Nara collection','Glavna zbirka Nara')+'</a> · <a href="Nara-AI-daily.html">'+b('Daily stories','Dnevne zgodbe')+'</a> · <a href="Nara-AI-archive.html">'+b('Archive','Arhiv')+'</a> · <a href="Nara-AI-log.html">'+b('Editorial log','Uredniški dnevnik')+'</a></p></footer>';
}
const tools='<div class="tools" role="group"'+aria('Reading controls','Nastavitve branja')+'><button type="button" data-scale="-0.1"'+aria('Smaller story text','Manjša pisava zgodbe')+'>A−</button><output data-scale-label aria-live="polite">100%</output><button type="button" data-scale="0.1"'+aria('Larger story text','Večja pisava zgodbe')+'>A+</button><button type="button" data-scale="reset"'+aria('Reset story text size','Ponastavi velikost pisave')+'>'+bi('Reset','Ponastavi')+'</button><button type="button" data-theme-toggle>'+bi('Day mode','Dnevni način')+'</button></div>';
const languageSwitch='<div class="language-switch" data-language-switch role="group"'+aria('Language','Jezik')+' hidden><button type="button" data-language="en" lang="en" aria-label="English" aria-pressed="true">EN</button><span aria-hidden="true">|</span><button type="button" data-language="sl" lang="sl" aria-label="Slovenščina" aria-pressed="false">SL</button></div>';
function shell(title,file,body,active='daily',localized=false){
  const b=localized?bi:(en)=>esc(en);
  const slTitle=active==='daily'?'Dnevne zgodbe':'Arhiv '+title.replace(' archive','');
  const description='Text-only Illuminara stories from GPT and Claude. Separate from the curated illustrated canon.';
  const slDescription='Besedilne zgodbe o Illuminari iz sodelovanja GPT in Clauda. Ločene od izbranega ilustriranega kanona.';
  return '<!doctype html>\n<html lang="en" data-theme="dark"'+(localized?' data-title-en="'+esc(title+' — Illuminara Daily')+'" data-title-sl="'+esc(slTitle+' — Illuminara Daily')+'"':'')+'><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark light"><meta name="theme-color" content="#080d15"><title>'+esc(title)+' — Illuminara Daily</title><meta name="description" content="'+description+'"'+(localized?' data-description-en="'+description+'" data-description-sl="'+slDescription+'"':'')+'><link rel="canonical" href="'+BASE+file+'"><link rel="stylesheet" href="assets/css/nara-daily.css?v='+VERSION+'"><script defer src="assets/js/nara-daily-reader.js?v='+VERSION+'"></script><!-- '+VERSION+'; generated, text-only --></head><body><a class="skip" href="#main">'+b('Skip to content','Preskoči na vsebino')+'</a><header class="bar"><div class="bar-inner"><a class="brand" href="Nara-AI-daily.html">'+b('ILLUMINARA / DAILY','ILLUMINARA / DNEVNO')+'</a><nav class="nav"'+aria('Primary','Glavna navigacija')+'><a href="index.html">'+b('Main collection','Glavna zbirka')+'</a><a href="illuminara.html">Illuminara</a><a href="Nara-AI-daily.html"'+(active==='daily'?' aria-current="page"':'')+'>'+b('Daily','Dnevno')+'</a><a href="Nara-AI-archive.html"'+(active==='archive'?' aria-current="page"':'')+'>'+b('Archive','Arhiv')+'</a><a href="Nara-AI-log.html"'+(active==='log'?' aria-current="page"':'')+'>'+b('Log','Dnevnik')+'</a></nav>'+(localized?languageSwitch:'')+'</div></header><main class="wrap" id="main" tabindex="-1">'+body+'</main>'+footer(localized)+'</body></html>\n';
}
const prose=(r,lang='en')=>'<article class="story" lang="'+lang+'" data-story-id="'+r.id+'" data-content-sha256="'+r.content_sha256+'" aria-label="'+(lang==='sl'?'Zgodba':'Story')+'">'+r.scenes.map((s,i)=>'<section><h2>'+String(i+1).padStart(2,'0')+' · '+esc(s.title)+'</h2>'+s.paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('\n')+'</section>').join('\n')+'</article>';
const notes=(r,lang='en')=>'<aside class="notes" lang="'+lang+'" aria-label="'+(lang==='sl'?'Uredniški opombi':'Editorial notes')+'"><details><summary>'+(lang==='sl'?'Kaj po mnenju kritika še ne deluje':"What the critic still says doesn't work")+'</summary><div class="inside"><p>'+esc(r.critic_line)+'</p></div></details><details><summary>'+(lang==='sl'?'Zasnova te zgodbe':"Tonight's shape")+'</summary><div class="inside"><p>'+esc(r.shape)+'</p></div></details></aside>';
const localizedText=(en,sl)=>sl?bi(en,sl):'<span lang="en">'+esc(en)+'</span>';
function storyContent(r,t){
  if(!t)return '<p class="translation-note" data-language-content="sl" lang="sl" hidden>Ta zgodba je trenutno na voljo v angleščini.</p>'+prose(r)+notes(r);
  return '<div data-language-content="en" lang="en">'+prose(r)+notes(r)+'</div><div data-language-content="sl" lang="sl" hidden><p class="translation-note">'+(t.translated_by?'Slovenski prevod: '+esc(t.translated_by)+'. ':'Slovenski prevod. ')+'Književna ocena velja za angleški izvirnik.</p>'+prose({...r,...t},'sl')+notes(t,'sl')+'</div>';
}
const scoreId=r=>'score-'+r.id;
const scoreChip=r=>{
  const v=r.literary_score;
  if(!v)return '';
  return '<span class="score-set"'+aria('Combined literary score','Skupna književna ocena')+'><button type="button" class="score-chip" data-score-open="'+scoreId(r)+'"'+aria('Open combined literary score explanation','Odpri razlago skupne književne ocene')+'>'+v.display+'</button></span>';
};
const scoreDialog=(r,t)=>{
  const v=r.literary_score;
  if(!v)return '';
  const id=scoreId(r),title=id+'-title',s=t?.literary_score;
  return '<dialog class="score-dialog" id="'+id+'" aria-labelledby="'+title+'"><div class="score-dialog-card"><form method="dialog" class="score-close-row"><button class="score-close"'+aria('Close score explanation','Zapri razlago ocene')+'>×</button></form><div class="eyebrow">'+bi('Combined blind literary score','Skupna slepa književna ocena')+'</div><h2 id="'+title+'">'+v.display+' / 100</h2><p class="score-method">'+localizedText(v.method,s?.method)+'</p><p>'+bi("Two locked evaluations of the English edition, one by GPT and one by Claude. Each counts 50%. The Editorial Log records the rubrics and evaluation provenance.",'Dve zaklenjeni oceni angleške različice, ena od GPT in ena od Clauda. Vsaka šteje 50 %. Uredniški dnevnik navaja lestvici in izvor ocen.')+'</p><h3>'+bi('Shared strengths','Skupno prepoznane odlike')+'</h3><ul>'+v.shared_strengths.map((x,i)=>'<li>'+localizedText(x,s?.shared_strengths[i])+'</li>').join('')+'</ul><h3>'+bi('Shared reservations','Skupni zadržki')+'</h3><ul>'+v.shared_reservations.map((x,i)=>'<li>'+localizedText(x,s?.shared_reservations[i])+'</li>').join('')+'</ul><p class="muted">'+bi('Exact raw evaluator scores and rubric names are preserved in the Editorial Log.','Natančni izvorni oceni in imeni ocenjevalnih lestvic so ohranjeni v uredniškem dnevniku.')+'</p><p><strong>'+bi('Unrounded combined score:','Skupna ocena pred zaokrožitvijo:')+'</strong> '+bi(v.combined.toFixed(1),v.combined.toFixed(1).replace('.',','))+'</p><p class="muted" data-language-content="sl" lang="sl" hidden>Ocena se nanaša na angleški izvirnik.</p></div></dialog>';
};
function revisionLabel(v){return v?'<small class="muted revision-label">'+bi('revised '+v.date,'prenovljeno '+v.date)+'</small>':''}
function revisionNotice(v){return v?'<p class="notice revision-note"><strong>'+bi('revised '+v.date+' · '+v.edition,'prenovljeno '+v.date+' · '+v.edition)+'</strong> · <a href="'+esc(v.original_url)+'">'+bi('Read the preserved original','Preberi ohranjeni izvirnik')+'</a> · <a href="'+esc(v.original_log_url)+'">'+bi('Original editorial log','Izvirni uredniški dnevnik')+'</a></p>':''}
function storyEntry(r,translations,daily){
  const t=translations[r.id]??r.translation_sl,href=daily?'Nara-AI-'+r.date.slice(0,7)+'.html#'+r.id:'#'+r.id;
  return '<details class="archive-item'+(daily?' daily-item':'')+'" id="'+r.id+'"><summary><time datetime="'+r.date+'">'+r.date+'</time><span class="story-summary-title"><strong>'+localizedText(r.title,t?.title)+'</strong>'+revisionLabel(r.revision)+scoreChip(r)+'</span></summary><div class="inside">'+revisionNotice(r.revision)+'<p class="lede">'+localizedText(r.deck,t?.deck)+'</p><p class="meta">'+bi('Published','Objavljeno')+' '+esc(r.published_at)+' · <a href="'+href+'">'+(daily?bi('Permanent archive link','Trajna povezava v arhiv'):bi('Permanent link','Trajna povezava'))+'</a></p>'+storyContent(r,t)+'</div></details>'+scoreDialog(r,t);
}
export function latestPage(input,month,translations={}){
  const records=(Array.isArray(input)?[...input]:(input?[input]:[])).sort((a,b)=>b.date.localeCompare(a.date));
  const header='<header class="masthead"><div class="eyebrow">'+bi('Nightly Illuminara fiction · one story each published day','Večerne Illuminarine zgodbe · po ena zgodba vsak dan z objavo')+'</div><h1>'+bi('Illuminara Daily','Illuminara · dnevne zgodbe')+'</h1><p class="lede">'+bi('Every published story stays on this page. Choose a date and title to open the full story; all stories are collapsed by default.','Vse objavljene zgodbe ostanejo na tej strani. Izberi datum in naslov, da odpreš celotno zgodbo; vse zgodbe so na začetku zaprte.')+'</p>'+tools+'</header>';
  const empty='<section class="notice"><h2>'+bi('The first story is not published yet.','Prva zgodba še ni objavljena.')+'</h2><p>'+bi('This reading lane is ready for the first completed GPT ↔ Claude cycle. Stories are released only after selection, editorial work and a reviewed final close.','Ta bralna zbirka je pripravljena na prvi zaključeni cikel GPT ↔ Claude. Zgodbe objavimo šele po izboru, uredniškem delu in pregledu končne različice.')+'</p></section><nav class="end-nav"><a href="Nara-AI-'+month+'.html">'+bi("This month's archive",'Arhiv tega meseca')+'</a><a href="Nara-AI-log.html">'+bi('Follow the editorial log','Spremljaj uredniški dnevnik')+'</a><a href="index.html">'+bi('Read the illustrated collection','Preberi ilustrirano zbirko')+'</a></nav>';
  return shell('Daily stories','Nara-AI-daily.html',header+(records.length?records.map(r=>storyEntry(r,translations,true)).join('\n'):empty),'daily',true);
}
export function monthlyPage(month,records,translations={}){
  assert(/^\d{4}-(0[1-9]|1[0-2])$/.test(month),'invalid month');
  const header='<header class="masthead"><div class="eyebrow">'+bi('Nightly stories · preserved editions','Večerne zgodbe · ohranjene izdaje')+'</div><h1>'+month+'</h1><p class="lede">'+bi('Open a date to read its complete story. Daily originals remain here when a separate illustrated edition is selected.','Odpri datum, da prebereš celotno zgodbo. Dnevni izvirniki ostanejo tukaj tudi, ko je izbrana ločena ilustrirana izdaja.')+'</p>'+tools+'</header>';
  const empty='<section class="notice"><h2>'+bi('No published stories yet.','Objavljenih zgodb še ni.')+'</h2><p>'+bi('Only completed, actually published stories appear in this archive. There are no invented entries for missed days.','V tem arhivu so samo zaključene in dejansko objavljene zgodbe. Za izpuščene dni ne ustvarjamo izmišljenih vnosov.')+'</p></section>';
  return shell(month+' archive','Nara-AI-'+month+'.html',header+(records.length?records.map(r=>storyEntry(r,translations,false)).join('\n'):empty),'archive',true);
}
export function originalEditionPage(r,translations={},revisedDate){
  validateRecord(r);assert(validDate(revisedDate),'original edition revision date');
  const header='<header class="masthead"><div class="eyebrow">'+bi('Preserved original edition','Ohranjena izvirna različica')+'</div><h1>'+localizedText(r.title,translations[r.id]?.title)+'</h1><p class="notice">'+bi('This is the original publication, preserved unchanged. The revised edition is dated '+revisedDate+'.','To je prvotna objava, ohranjena brez sprememb. Prenovljena različica ima datum '+revisedDate+'.')+'</p>'+tools+'</header>';
  const links='<nav class="end-nav"><a href="Nara-AI-'+r.date.slice(0,7)+'.html#'+r.id+'">'+bi('Read the revised edition','Preberi prenovljeno različico')+'</a><a href="Nara-AI-'+r.date+'-original-log.html">'+bi('Original editorial log','Izvirni uredniški dnevnik')+'</a></nav>';
  return shell('Original edition — '+r.title,'Nara-AI-'+r.date+'-original.html',header+storyEntry(r,translations,false)+links,'archive',true);
}
export function archivePage(entries,emptyMonth){const months=[...new Set(entries.map(e=>e.date.slice(0,7)).concat(emptyMonth?[emptyMonth]:[]))].sort().reverse();return shell('The nightly archive','Nara-AI-archive.html',`<header class="masthead"><div class="eyebrow">Illuminara · text-only experiments</div><h1>The nightly archive</h1><p class="lede">A shelf of complete stories. A place to return, not a feed to keep up with.</p></header><ul class="months">${months.map(m=>`<li><a href="Nara-AI-${m}.html"><strong>${m}</strong><br><span class="muted">${entries.filter(e=>e.date.startsWith(m)).length} published stories</span></a></li>`).join('')}</ul>${entries.some(e=>e.revision)?`<section class="notice"><h2>Preserved original editions</h2><ul>${entries.filter(e=>e.revision).map(e=>`<li>${esc(e.date)} · <a href="${esc(e.revision.original_url)}">${esc(e.title)} — original</a> · revised ${esc(e.revision.date)}</li>`).join('')}</ul></section>`:''}<section class="notice"><h2>Daily first. Illustrated by choice.</h2><p>These stories belong to the experimental Illuminara lane. BD and the editorial partner may choose a story for a separately approved illustrated edition. The Daily original is retained; nothing becomes canon automatically.</p></section>`,'archive')}
export function logPage(logs,options={}){const sorted=[...logs].sort((a,b)=>b.date.localeCompare(a.date));assert(!options.original||sorted.length===1,'one original log required');const file=options.original?'Nara-AI-'+sorted[0].date+'-original-log.html':'Nara-AI-log.html';return shell(options.original?'Original editorial log':'Editorial log',file,`<header class="masthead"><div class="eyebrow">GPT × Claude · how each story changed</div><h1>${options.original?'Original editorial log — preserved':'Illuminara Daily · Log'}</h1><p class="lede">The public editorial trail behind each nightly story: the ten candidates, the selection, the useful objections, the revisions and the closing verdict. Operational telemetry stays private.</p></header>${sorted.length?sorted.map(l=>`<details class="log-entry" id="${l.id}"><summary><time datetime="${l.date}">${l.date}</time><strong>${esc(l.title)}</strong>${revisionLabel(l.revision)}</summary><div class="inside">${revisionNotice(l.revision)}<p class="roleline"><strong>${esc(l.author)}</strong> wrote the prose · <strong>${esc(l.critic)}</strong> selected and edited</p><h3>Ten candidates</h3><ol class="candidate-list">${l.candidates.map(c=>`<li><strong>${esc(c.title)}</strong><span>${esc(c.premise)}</span></li>`).join('')}</ol><section class="log-selection"><h3>Selected: ${esc(l.selection.title)}</h3><p>${esc(l.selection.reason)}</p><p class="muted"><strong>Risk to watch:</strong> ${esc(l.selection.risk)}</p></section><h3>Editorial rounds</h3><ol class="rounds">${l.rounds.map(r=>`<li><span class="round-stage">${esc(r.actor)} · ${esc(r.stage.replaceAll('_',' '))}</span><p>${esc(r.summary)}</p></li>`).join('')}</ol><blockquote class="critic-line">${esc(l.final_critic_line)}</blockquote>${l.evaluation?`<details class="score-audit"><summary>Blind literary evaluation · combined ${l.evaluation.display}</summary><div class="inside"><p><strong>GPT:</strong> ${l.evaluation.gpt.score} / 100 · ${esc(l.evaluation.gpt.rubric)}</p><p><strong>Claude:</strong> ${l.evaluation.claude.score} / 100 · ${esc(l.evaluation.claude.rubric)}</p><p><strong>Combined:</strong> ${l.evaluation.combined.toFixed(1)} → ${l.evaluation.display} · equal 50/50 weight</p><p class="muted">${esc(l.evaluation.note)}</p></div></details>`:''}<nav class="end-nav"><a href="${options.original?`Nara-AI-${l.date}-original.html`:`Nara-AI-${l.date.slice(0,7)}.html`}#NARA-D-${l.date}">Read the published story</a></nav></div></details>`).join('\n'):`<section class="notice"><h2>The first editorial log is not published yet.</h2><p>When tonight’s story is released, this page will preserve a readable summary of how GPT and Claude chose, challenged and improved it. Private IDs, hashes, prompts and scheduler telemetry never appear here.</p></section>`}`,'log')}
function write(p,s){fs.mkdirSync(path.dirname(p),{recursive:true});if(fs.existsSync(p)&&fs.readFileSync(p,'utf8')===s)return;const tmp=p+'.tmp';fs.writeFileSync(tmp,s);fs.renameSync(tmp,p)}
const stringify=x=>JSON.stringify(x,null,2)+'\n';
export function loadRecords(root){const n=path.join(root,'public/Nara');const c=validateCatalog(JSON.parse(fs.readFileSync(path.join(n,'daily/catalog.json'),'utf8')));return {n,c,records:c.records.map(e=>{const bytes=fs.readFileSync(path.join(n,e.file),'utf8');assert(hash(bytes)===e.record_sha256,'record byte hash mismatch');const r=validateRecord(JSON.parse(bytes));assert(r.id===e.id&&r.date===e.date&&r.title===e.title,'catalog record mismatch');return r}).sort((a,b)=>b.date.localeCompare(a.date))}}
export function initialize(root,month){assert(/^\d{4}-(0[1-9]|1[0-2])$/.test(month),'invalid month');const n=path.join(root,'public/Nara');const cp=path.join(n,'daily/catalog.json');if(!fs.existsSync(cp))write(cp,stringify({schema:'nara.daily.catalog.v1',records:[]}));const {c,records}=loadRecords(root);assert(records.length===0,'init refuses existing stories');write(path.join(n,'Nara-AI-daily.html'),latestPage(null,month));write(path.join(n,`Nara-AI-${month}.html`),monthlyPage(month,[]));write(path.join(n,'Nara-AI-archive.html'),archivePage(c.records,month));write(path.join(n,'Nara-AI-log.html'),logPage([]));return 'INITIALIZED_EMPTY_NOT_STORY_PUBLISHED'}
export function publish(root,record,logRecord,now=new Date()){const r=validateRecord(record),l=validateLog(logRecord);assert(l.date===r.date&&l.story_id===r.id&&l.title===r.title,'story/log mismatch');assert(l.final_critic_line===r.critic_line,'critic line mismatch');assert(new Date(r.published_at).getTime()<=now.getTime(),'future publication time');const p=localParts(now.toISOString());assert(`${p.year}-${p.month}-${p.day}`===r.date,'not current local publication date');const {n,c,records}=loadRecords(root);const bytes=stringify(r),logBytes=stringify(l);const existing=c.records.find(e=>e.date===r.date);if(existing){assert(existing.record_sha256===hash(bytes),'duplicate date with different contents');assert(existing.log_sha256===hash(logBytes),'duplicate date with different log');assert(hash(fs.readFileSync(path.join(n,existing.log_file),'utf8'))===existing.log_sha256,'duplicate date with different log');return 'ALREADY_PUBLISHED'}assert(!records.some(x=>x.date>r.date),'backfill prohibited');const file=`daily/records/${r.date}.json`,logFile=`daily/log/${r.date}.json`;for(const [fp,data,label] of [[path.join(n,file),bytes,'orphan conflict'],[path.join(n,logFile),logBytes,'orphan log conflict']])if(fs.existsSync(fp))assert(fs.readFileSync(fp,'utf8')===data,label);const next=[r,...records].sort((a,b)=>b.date.localeCompare(a.date));const entries=[...c.records,{id:r.id,date:r.date,title:r.title,file,record_sha256:hash(bytes),log_file:logFile,log_sha256:hash(logBytes)}].sort((a,b)=>b.date.localeCompare(a.date));const allLogs=entries.filter(e=>e.log_file).map(e=>{const b=e.date===l.date?logBytes:fs.readFileSync(path.join(n,e.log_file),'utf8');assert(hash(b)===e.log_sha256,'log byte hash mismatch');return validateLog(JSON.parse(b))});const month=r.date.slice(0,7);const translations=loadTranslations(root,next);const outputs={[file]:bytes,[logFile]:logBytes,'Nara-AI-daily.html':latestPage(next,month,translations),[`Nara-AI-${month}.html`]:monthlyPage(month,next.filter(x=>x.date.startsWith(month)),translations),'Nara-AI-archive.html':archivePage(entries,month),'Nara-AI-log.html':logPage(allLogs),'daily/catalog.json':stringify({schema:'nara.daily.catalog.v1',records:entries})};for(const [rel,data]of Object.entries(outputs))write(path.join(n,rel),data);return 'LOCAL_CANDIDATE_READY_COMMIT_ALL_SEVEN_FILES_ATOMICALLY'}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const [cmd,root,arg,arg2]=process.argv.slice(2);assert(root,'repoRoot required');if(cmd==='init')console.log(initialize(root,arg));else if(cmd==='publish'){assert(arg&&arg2,'story and log record files required');console.log(publish(root,JSON.parse(fs.readFileSync(arg,'utf8')),JSON.parse(fs.readFileSync(arg2,'utf8'))))}else if(cmd==='check'){const {records}=loadRecords(root);console.log(JSON.stringify({schema:'nara.daily.validation.v2',records:records.length,logs:records.filter(r=>r.log_file).length,result:'STATIC_VALID',peer_authenticity:'NOT_CHECKED_BY_RENDERER'}))}else throw Error('use init, publish or check')}catch(e){console.error(e.message);process.exitCode=1}}
